name: Dangerous PR Target Experiment

on:
  pull_request_target:

jobs:
  dangerous:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}

      - name: Inspect checkout
        run: |
            git rev-parse HEAD
            git status
            ls -la
            find . -maxdepth 3 -type f

      - name: Run PR code
        run: |
          echo "Running code from the PR"
          python scripts/pr-code.py