name: Permission scope experiment

on:
  workflow_dispatch:

permissions: {}

jobs:
  read-job:
    runs-on: ubuntu-latest
    steps:
      - name: Read repository
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/${{ github.repository }}

      - name: Try to create issue
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
            gh api \
            --method POST \
            repos/${{ github.repository }}/issues \
            -f title="Should fail - read job"

  write-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Create issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
          --method POST \
          repos/${{ github.repository }}/issues \
          -f title="Job permission test"