name: PR branch trigger

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  pr-branch-test:
    runs-on: ubuntu-latest

    steps:
      - name: Show message
        run: echo "This PR targets main"