name: Vulnerable workflow


on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true

concurrency:
  group: workflow-security-review
  cancel-in-progress: true

jobs:
  
  test:
    name: Vulnerable job
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: echo "Hello ${{ github.event.inputs.name }}"